services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: bisbis10
      POSTGRES_PASSWORD: bisbis10
      POSTGRES_DB: bisbis10
    #volumes:
    #  - type: bind
    #    source: ./data
    #    target: /var/lib/postgresql/data
    ports:
      - target: 5432
        published: 5432
        protocol: tcp